### Creating a host user

POST http://localhost:3000/users/create
Content-Type: application/json 

{
    "name":"Yannick Zahinda",
    "email":"ymulikuza@gmail.com",
    "role":"host"
}

### Creating a rental user

POST http://localhost:3000/users/create
Content-Type: application/json

{
    "name":"Jane Renter",
    "email":"renter@example.com",
    "role":"renter"
}

### Get all users

GET http://localhost:3000/users/all

### Deleting a user

DELETE http://localhost:3000/users/1